# Generated by Django 3.0.2 on 2020-01-31 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleCode', models.CharField(max_length=10)),
                ('moduleName', models.CharField(max_length=30)),
                ('moduleTeacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('studentsEnrolled', models.ManyToManyField(blank=True, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
